### ISSUE TITLE
Exiting due to PROVIDER_KVM2_ERROR  (POPOS)

### ISSUE THREAD

**Issue by Karthik-PM** [dzintars/infra#70]
i am getting this error while running minikube start
![image](https://user-images.githubusercontent.com/72903849/200035188-feb90c9b-9301-454f-989a-0ead841e7736.png)

**Comment by dzintars** [comment]
Are your user member of `libvirt` group?

**Comment by Karthik-PM** [comment]
@dzintars  i did a `sudo adduser id -un libvirtd `  
is there a command to check if i am a member?

**Comment by dzintars** [comment]
I'm just suggesting things you can check. I's hard to say what could go wrong in your particular setup. So:
Check `/etc/libvirt/libvirtd.conf` and make sure you have these lines enabled/added:
```ini
unix_sock_group = "libvirt"
unix_sock_rw_perms = "0770"
```
And in `/etc/libvirt/qemu.conf`:
```ini
user = "your-user-name"
group = "your-user-group"
```

This should give the right permissions for you to run VMs without privilege escalation.

Also you can create `/home/your-user-name/.config/libvirt/libvirt.conf` file and to set default qemu path:
```ini
uri_default = "qemu:///system"
```

**P.S.** I don't maintain this repository for quite some time... so. Take it as is.

**Comment by Karthik-PM** [comment]
> I'm just suggesting things you can check. I's hard to say what could go wrong in your particular setup. So: Check `/etc/libvirt/libvirtd.conf` and make sure you have these lines enabled/added:
> 
> ```ini
> unix_sock_group = "libvirt"
> unix_sock_rw_perms = "0770"
> ```
> 
> And in `/etc/libvirt/qemu.conf`:
> 
> ```ini
> user = "your-user-name"
> group = "your-user-group"
> ```
> 
> This should give the right permissions for you to run VMs without privilege escalation.
> 
> Also you can create `/home/your-user-name/.config/libvirt/libvirt.conf` file and to set default qemu path:
> 
> ```ini
> uri_default = "qemu:///system"
> ```
> 
> **P.S.** I don't maintain this repository for quite some time... so. Take it as is.

i am getting user = qemu 
and group as root .. is that how its supposed to be?
![image](https://user-images.githubusercontent.com/72903849/200153700-4cbf2886-2f37-485f-9433-55a8d634271a.png)

**Comment by Karthik-PM** [comment]
@dzintars  i solved the issue by giving permission at /var/kvm  by typing 
`sudo chmod +666 /dev/kvm`
and  /var/run/libvirt/ 
using `sudo chmod -R +777 libvirt`
